### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by juliangums** [tdondich/triforce#3]
Hey! I’ve seen you demoing this at Laracon. First of all: GREAT WORK! I’ve built some complex 3D simulations (not games but technically it’s the same). I wouldn’t consider myself an expert but I had a look at your code and realised you’re using 2D canvas context. I would normally use WebGL for that. From what people say WebGL seems to be faster. Maybe you can increase performance that way. You can use three.js to develop it a little quicker but it might be adding an additional overhead. All in all in my experience it is always difficult to build stuff like that for the browser. I think I’ve seen some benchmark tests that show in-browser-JavaScript runs about 20x slower than native code.
Another trick that I use to avoid the high cpu load is that I’m bypassing client-side load by doing most of my computations server-side and then broadcast it in a WebGL ready Format via websockets. Not really feasible in your case though because of delays.
There are a lot of micro-optimisations as well of course but as you said cpu load will go up when you fix the outstanding bugs. Unfortunately browsers just aren’t built for games so you just have to accept the fact that it won’t be nearly as fast as if it was running on the OS directly.
Hope I could help. Keep up the good work!

**Comment by tdondich** [comment]
Hi there and thanks for your comments.  Unfortunately, webgl wouldn't work in this situation because I'm technically not using full sprites or drawing.  This is literally using pixel by pixel rendering based on how the NES PPU renders to a television screen.  So in that situation, the Canvas is the more appropriate choice.  And technically, I've implemented a frame buffer so drawing to the buffer is extremely quick and then when it's time to render a new frame, the framebuffer is just dropped into the canvas.  This is by far the fastest way to "render" to the browser what the NES is doing.

Yeah, don't want this running in server.  Ideally everything is running in client-side JS.  However, there's certainly appears to be slowness.  The chrome performance tools aren't the best at REALLY looking deep into the V8 javascript engine, so I'm still trying to figure out the best tooling for doing the micro-optimizations.  The good news is, even if they're micro-optimizations, because the cpu emulation is doing over a millions instructions a second and the PPU is doing 3x, any micro-optimization goes a loooong way.

Thanks for following!  I'll keep at it.  I'll close this ticket as there's no bug reported, but will continue to progress.
